<<echo=FALSE, results=hide>>=

if (lan == 'en') {
  question.1 <- 'If you are working in a directory of your computer called \\verb|C:/MyCode| and you want to change the directory to a subfolder called \\verb|data|, which of the following commands will do that?'
  
}

if (lan == 'pt-br') {
  question.1 <- 'Caso estejas trabalhando com o R em um diretório do seu computador chamado \\verb|C:/MyCode| e queira mudar o diretório de trabalho para um subdiretório chamado \\verb|data|, qual dos comandos abaixo irá atingir este objetivo?'
  
}

@

\begin{question}

<<echo=False, results=tex>>=
cat(paste(question.1,collapse = ""))
@


\begin{answerlist}
\item \verb|setwd(paste0(getwd(),'/data'))|
\item \verb|setwd(paste(getwd(),'/data'))|
\item \verb|setwd(getwd())|
\item \verb|getwd(paste0(setwd(),'data'))|
\item \verb|getwd(paste(getwd(),'data'))|
\end{answerlist}

\end{question}

\begin{solution}
\begin{answerlist}
  \item True.
  \item False.
  \item False.
  \item False.
  \item False. 
\end{answerlist}
\end{solution}

%% META-INFORMATION
\extype{schoice}
\exsolution{10000}
\exname{Q.1}
\exshuffle{TRUE}

